from __future__ import annotations

from typing import Any, Protocol


class PersistenceAdapter(Protocol):
    async def save(self, entity: Any) -> None: ...
    async def load(self, entity_id: str) -> Any | None: ...
    async def delete(self, entity_id: str) -> None: ...
    def drain_all(self) -> None: ...
